spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airline
    username: lenadelrey
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false